export const data =  [
    {
      id:0,
      type: 'Apartment',
      title:'1 room',
      description:'test description',
      price: 50000,
      image: 'jarek-ceborski-jn7uVeCdf6U-unsplash.jpg',
      new: true,
      size: 194,
      location: 'Antakalnio',
    },
    {
      id:1,
      type: 'Apartment',
      title:'2 room apartment in Vilnius',
      description:'test description',
      price: 65000,
      image: 'jarek-ceborski-jn7uVeCdf6U-unsplash.jpg',
      new: false,
      size: 52,
      location: 'Vilnius',
    },
    {
        id:2,
        type: 'House',
        title:'2 room apartment in Vilnius',
        description:'test description',
        price: 65000,
        image: 'jarek-ceborski-jn7uVeCdf6U-unsplash.jpg',
        new: false,
        size: 95,
        location: 'Palanga',
      }
]